// Code generated by gotemplate. DO NOT EDIT.

package optional

import (
	"database/sql/driver"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"time"

	"github.com/imiskolee/optional/optional_scanner"
)

var _Bool = time.Time{}
var __Bool = optional_scanner.ScanBool

// template type Optional(T,scan)

//swagger:type bool
type Bool optionalBool

type optionalBool []bool

const (
	valueKeyBool = iota
)

func scanValueBool(input string) (val bool, err error) {
	v, err := optional_scanner.ScanBool(input)
	return bool(v), err
}

// Of wraps the value in an optional.
func OfBool(value bool) Bool {
	return Bool{valueKeyBool: value}
}

func OfBoolPtr(ptr *bool) Bool {
	if ptr == nil {
		return EmptyBool()
	} else {
		return OfBool(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyBool() Bool {
	return nil
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Bool) Get() (value bool, ok bool) {
	o.If(func(v bool) {
		value = v
		ok = true
	})
	return
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Bool) IsPresent() bool {
	return o != nil
}

// If calls the function if there is a value wrapped by this optional.
func (o Bool) If(f func(value bool)) {
	if o.IsPresent() {
		f(o[valueKeyBool])
	}
}

func (o Bool) ElseFunc(f func() bool) (value bool) {
	if o.IsPresent() {
		o.If(func(v bool) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Bool) Else(elseValue bool) (value bool) {
	return o.ElseFunc(func() bool { return elseValue })
}

// V returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Bool) V() (value bool) {
	var zero bool
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Bool) String() string {
	if o.IsPresent() {
		return fmt.Sprintf("%v", o.V())
	}
	return fmt.Sprintf("%v", nil)
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Bool) MarshalJSON() (data []byte, err error) {
	if o.IsPresent() {
		return json.Marshal(o[valueKeyBool])
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Bool) UnmarshalJSON(data []byte) error {
	var v bool
	err := json.Unmarshal(data, &v)
	//Try unmarshal string numbers with quote
	if err != nil && len(data) > 2 {
		cpy := data[1 : len(data)-2]
		err = json.Unmarshal(cpy, &v)
	}
	if err != nil {
		return err
	}

	*o = OfBool(v)
	return nil
}

// MarshalXML marshals the value being wrapped to XML. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Bool) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(o.V(), start)
}

// UnmarshalXML unmarshals the XML into a value wrapped by this optional.
func (o *Bool) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var v bool
	err := d.DecodeElement(&v, &start)
	if err != nil {
		return err
	}
	*o = OfBool(v)
	return nil
}

func (c Bool) Value() (driver.Value, error) {
	v, ok := c.Get()
	if ok {
		return driver.DefaultParameterConverter.ConvertValue(v)
	}
	return driver.DefaultParameterConverter.ConvertValue(nil)
}

func (c *Bool) Scan(input interface{}) (err error) {
	var vv string
	var isvalid = true

	if input == nil {
		isvalid = false
	}

	if isvalid {
		switch value := input.(type) {
		case string:
			vv = value
		case []byte:
			if value != nil {
				vv = string(value)
			} else {
				isvalid = false
			}
		default:
			vv = fmt.Sprint(input)
		}
	}

	if isvalid {
		val, err := scanValueBool(vv)
		if err != nil {
			return err
		}
		*c = OfBool(val)
	}
	return
}
