package optional

//go:generate gotemplate "github.com/imiskolee/optional/templates" Bool(bool)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Byte(byte)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Complex128(complex128)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Complex64(complex64)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Float32(float32)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Float64(float64)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Int(int)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Int16(int16)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Int32(int32)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Int64(int64)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Int8(int8)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Rune(rune)
//go:generate gotemplate "github.com/imiskolee/optional/templates" String(string)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uint(uint)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uint16(uint16)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uint32(uint32)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uint64(uint64)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uint8(uint8)
//go:generate gotemplate "github.com/imiskolee/optional/templates" Uintptr(uintptr)
